const CONFIG = {
    titleWeb: "Tiêu đề web",
    introTitle: 'hello babby',
    introDesc: `:)))`,
    btnIntro: 'lẹt gô',
    title: 'hay mình làm bồ nhau đi Huy nhỉ :))?',
    desc: 'thoát ra là tao đấm vô mặt mày',
    btnYes: 'oke',
    btnNo: 'không',
    question: 'ơ kìa tại sao tại sao :))',
    btnReply: 'gửi',
    reply: '....',
    mess: ':))))))))))))',
    messDesc: 'rồi rồi qua mes lại đi',
    btnAccept: 'ok',
    messLink: 'https://www.facebook.com/messages/t/100059059906136}
