const CONFIG = {
    titleWeb: "Tiêu đề web",
    introTitle: 'helloo babyy',
    introDesc: `:)))`,
    btnIntro: 'lét gô',
    title: 'hay là mình làm bồ nhau nhỉ?',
    desc: 'thoát ra tao đấm vô mặt ',
    btnYes: 'oke',
    btnNo: 'Không',
    question: 'ơ kìa tại sao tại sao :)))',
    btnReply: 'Gửi',
    reply: '.....',
    mess: 'thế cơ à :))',
    messDesc: 'qua bên mes đi',
    btnAccept: 'ok',
    messLink: 'https://github.com/zukahai/Confess-Crush' //100059059906136
